package constants

type LANGUAGE_ENUM string

const (
	LANGUAGE_ENUM_VN  LANGUAGE_ENUM = "VN"
	LANGUAGE_ENUM_CN  LANGUAGE_ENUM = "CN"
	LANGUAGE_ENUM_JPN LANGUAGE_ENUM = "JPN"
	LANGUAGE_ENUM_KR  LANGUAGE_ENUM = "KR"
	LANGUAGE_ENUM_US  LANGUAGE_ENUM = "US"
)
